interface=ens18
driver=wired
logger_syslog=-1
logger_stdout=-1
logger_syslog_level=2
logger_stdout_level=2

ieee8021x=1
eap_reauth_period=3600

# RADIUS server
auth_server_addr=192.168.190.13
auth_server_port=1812
auth_server_shared_secret=testing123

acct_server_addr=192.168.190.13
acct_server_port=1813
acct_server_shared_secret=testing123
