interface=wlan0
driver=nl80211
logger_syslog=-1
logger_stdout=-1
logger_syslog_level=2
logger_stdout_level=2

ssid=nanoart
hw_mode=g
channel=6
ieee80211n=1
wmm_enabled=1

# WPA2-Enterprise (802.1X)
wpa=2
wpa_key_mgmt=WPA-EAP
rsn_pairwise=CCMP
ieee8021x=1
eap_reauth_period=3600

# RADIUS server
auth_server_addr=192.168.190.37
auth_server_port=1812
auth_server_shared_secret=testing123

#acct_server_addr=192.168.190.37
#acct_server_port=1813
#acct_server_shared_secret=testing123
